
# Docker Hub 의 우분투 18.04 이미지 호출
FROM ubuntu:18.04

# 패키지 설치
RUN apt update -y && apt upgrade -y

RUN apt install -y vim git unzip sendmail software-properties-common build-essential

# qwerty
RUN echo 'LANG="en_US.UTF-8"' > /etc/default/locale

# APT server > 카카오 
# RUN echo 'deb http://mirror.kakao.com/ubuntu bionic main restricted universe multiverse' > /etc/apt/sources.list
# RUN echo 'deb http://mirror.kakao.com/ubuntu bionic-updates main restricted universe multiverse' >> /etc/apt/sources.list
# RUN echo 'deb http://security.ubuntu.com/ubuntu bionic-security main restricted universe multiverse' >> /etc/apt/sources.list

# 서울로 시간 변경
RUN ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime

# hostname 설정 및 적용
RUN echo 'localhost' > /etc/hostname
# RUN hostname -F /etc/hostname

# myserver1 서버네임
RUN echo '127.0.0.1    myserver1' >> /etc/hosts
# RUN sed -i "s/preserve_hostname: false/preserve_hostname: true/i" /etc/cloud/cloud.cfg


# 메일 호스트네임 설정
RUN echo "localhost" > /etc/mail/local-host-names

# 아파치 설치
RUN apt install -y apache2
RUN apt install ssl-cert certbot
RUN a2enmod rewrite
RUN a2enmod headers
RUN a2enmod ssl
RUN a2dismod -f autoindex
RUN service apache2 restart
RUN apache2ctl -S

# 기본 언어셋 UTF-8 설정 
RUN sed -i "s/# AddDefaultCharset UTF-8/AddDefaultCharset UTF-8/i" /etc/apache2/conf-available/charset.conf

# 추가 보안 설정
RUN sed -i "s/# AddDefaultCharset UTF-8/AddDefaultCharset UTF-8/i" /etc/apache2/conf-available/security.conf


